import type { EndpointDefinition, Locale, Workflow } from "./types.ts";

export const REPOSITORY_URL =
  "https://github.com/4x25/agnes-compatible-gateway";

export const ENDPOINTS: EndpointDefinition[] = [
  {
    id: "chat",
    method: "POST",
    path: "/v1/chat/completions",
    labels: { en: "Chat", "zh-CN": "文本补全" },
  },
  {
    id: "image",
    method: "POST",
    path: "/v1/images/generations",
    labels: { en: "Text to image", "zh-CN": "文生图" },
  },
  {
    id: "edit",
    method: "POST",
    path: "/v1/images/edits",
    labels: { en: "Image to image", "zh-CN": "图生图" },
  },
  {
    id: "textVideo",
    method: "POST",
    path: "/v1/videos",
    labels: { en: "Text to video", "zh-CN": "文生视频" },
  },
  {
    id: "imageVideo",
    method: "POST",
    path: "/v1/videos",
    labels: { en: "Image to video", "zh-CN": "图生视频" },
  },
];

export const DEFAULT_MODELS: Record<Workflow, string> = {
  chat: "agnes-2.0-flash",
  image: "agnes-image-2.1-flash",
  edit: "agnes-image-2.1-flash",
  textVideo: "agnes-video-v2.0",
  imageVideo: "agnes-video-v2.0",
};

/**
 * All prose is centralized here so switching language never changes the page's
 * information architecture. API paths, field names, and code remain unlocalized.
 */
export const COPY = {
  en: {
    skip: "Skip to main content",
    nav: {
      playground: "Live test",
      compatibility: "Compatibility",
      quickstart: "Quick start",
      deploy: "Deploy",
      faq: "FAQ",
      menu: "Open navigation",
      close: "Close navigation",
      github: "View GitHub repository",
      theme: "Toggle color theme",
      locale: "Switch to Simplified Chinese",
    },
    hero: {
      eyebrow: "OPENAI-COMPATIBLE GATEWAY",
      titleA: "One OpenAI shape.",
      titleB: "Every Agnes modality.",
      body:
        "Use existing OpenAI clients for Agnes chat, image, image-editing, and video generation—without a server-side API key or hidden model mapping.",
      primary: "Test it now",
      secondary: "View on GitHub",
      proof: ["Open source", "Self-hosted", "Keys never persisted"],
      curl: "cURL",
      sdk: "OpenAI SDK",
      copy: "Copy example",
      copied: "Copied",
    },
    playground: {
      eyebrow: "USE YOUR OWN KEY",
      title: "Run a real request",
      intro:
        "Requests go directly from this browser to the gateway you select. Your Agnes key stays only in this page's memory.",
      key: "Agnes API key",
      keyHint: "Never saved to cookies, localStorage, or analytics.",
      show: "Show key",
      hide: "Hide key",
      clear: "Clear sensitive data",
      base: "Gateway base URL",
      baseHint: "The current deployment is used by default.",
      advanced: "Connection settings",
      destination: "Request destination",
      model: "Model",
      prompt: "Prompt",
      message: "Message",
      promptPlaceholder: "Describe what you want Agnes to create…",
      messagePlaceholder: "Explain why gateways are useful in two sentences.",
      stream: "Stream the response",
      size: "Size",
      count: "Images",
      seconds: "Duration",
      image: "Reference image",
      drop: "Choose a PNG, JPEG, or WebP image",
      fileLimit: "One image, up to 20 MiB.",
      remove: "Remove image",
      send: "Send request",
      cancel: "Cancel",
      retry: "Retry",
      requiredKey: "Enter your Agnes API key.",
      requiredModel: "Model is required and is passed through unchanged.",
      requiredPrompt: "Enter a prompt or message.",
      requiredImage: "Choose an image for this workflow.",
      invalidImage: "Choose a PNG, JPEG, or WebP image no larger than 20 MiB.",
      invalidBase: "Enter an absolute http:// or https:// gateway URL.",
      request: "Request",
      result: "Result",
      empty: "Your response will appear here.",
      requesting: "Waiting for Agnes…",
      polling: "Video accepted. Polling the task…",
      success: "Completed",
      failed: "Request failed",
      cancelled: "Cancelled",
      status: "HTTP status",
      elapsed: "Elapsed",
      task: "Task ID",
      requestId: "Request ID",
      progress: "Task progress",
      rawRequest: "Sanitized request",
      rawResponse: "Raw response",
      copyJson: "Copy JSON",
      download: "Download",
      openMedia: "Open media",
      noPersistence:
        "The inspector redacts Authorization and keeps response bodies in memory only.",
    },
    compatibility: {
      eyebrow: "EXPLICIT, NOT MAGICAL",
      title: "Know exactly what changes",
      intro:
        "The gateway transforms only the mismatches it can resolve safely. Models are always passed through unchanged.",
      all: "All",
      text: "Text",
      images: "Images",
      video: "Video",
      differences: "Only differences",
      capability: "Capability / route",
      request: "OpenAI input",
      mapping: "Gateway behavior",
      status: "Support",
      pass: "Pass-through",
      transform: "Transformed",
      partial: "Partial",
      extension: "Agnes extension",
      rows: [
        [
          "Chat",
          "model, messages, stream",
          "Model passes through; developer becomes system; max_completion_tokens becomes max_tokens.",
          "transform",
        ],
        [
          "Image generation",
          "prompt, model, size, n",
          "Defaults size to 1024x1024; response_format is converted; n fans out atomically.",
          "transform",
        ],
        [
          "Image edits",
          "multipart image / image[]",
          "Files become Data URIs in Agnes extra_body.image.",
          "transform",
        ],
        [
          "Video creation",
          "prompt, seconds, size",
          "seconds becomes 24 fps frame count; size is split into width and height.",
          "transform",
        ],
        [
          "Video retrieval",
          "GET /v1/videos/{id}",
          "The public ID is the stateless Agnes task ID.",
          "pass",
        ],
        [
          "Video content",
          "GET /v1/videos/{id}/content",
          "Completed media is streamed; thumbnail and spritesheet variants fall back to video.",
          "partial",
        ],
      ],
    },
    security: {
      eyebrow: "REQUEST TRANSPARENCY",
      title: "Your credential has a short path",
      steps: ["This browser", "Your gateway", "Agnes AI"],
      body:
        "The production gateway has no server-side API key. It forwards the Bearer credential supplied for each request, and logs only redacted request metadata.",
      memory: "Key lifecycle",
      memoryBody:
        "Component memory only; clear it at any time or close the tab.",
      storage: "Not persisted",
      storageBody:
        "Keys, media, prompts, and responses never enter localStorage.",
      audit: "Auditable",
      auditBody: "Follow the request path in the open-source route handlers.",
      source: "Inspect the source",
    },
    quickstart: {
      eyebrow: "FIVE-MINUTE START",
      title: "Point your client at the gateway",
      intro:
        "Keep your Agnes model name and API key. Change only the OpenAI client's base URL.",
      sdk: "OpenAI SDK",
      curl: "cURL",
      docker: "Docker",
      deno: "Deno Deploy",
      dockerBody:
        "Run the published image with one optional upstream URL. No database or secrets service is required.",
      denoBody:
        "Fork the repository, connect it to Deno Deploy, and use the Fresh preset. The default Agnes endpoint works without configuration.",
      env: "Optional environment variable",
      deployLink: "Read deployment guide",
    },
    troubleshooting: {
      eyebrow: "DIAGNOSE FROM THE EDGE",
      title: "Common failures are kept visible",
      items: [
        [
          "401 / 403",
          "Check the Agnes key and whether it can use the requested model. The gateway never substitutes another credential.",
        ],
        [
          "404",
          "Verify the gateway base URL and compatible route. Video APIs use /v1/videos, not /v1/video/generations.",
        ],
        [
          "429",
          "The response comes from Agnes account limits. Inspect Retry-After and the raw response before retrying.",
        ],
        [
          "Invalid parameters",
          "Confirm the model, image type, size, and video duration. Ignored optional fields are listed in the response headers.",
        ],
        [
          "5xx or timeout",
          "Media jobs can be long-running. Check gateway logs by request ID; use Docker if an edge runtime deadline is too short.",
        ],
      ],
    },
    faq: {
      eyebrow: "FAQ",
      title: "Straight answers",
      items: [
        [
          "Is this an official Agnes AI project?",
          "No. It is an independent, open-source compatibility gateway built against the public Agnes API documentation.",
        ],
        [
          "Does the gateway store my API key?",
          "No. Production has no server-side key. This tester keeps your key in memory only and sends it with each request.",
        ],
        [
          "Which models are supported?",
          "The gateway does not maintain a model catalog or aliases. Supply any model name your Agnes account supports.",
        ],
        [
          "Why can a response differ from OpenAI?",
          "Some Agnes capabilities have no exact OpenAI equivalent. The compatibility matrix documents every pass-through, conversion, and partial behavior.",
        ],
        [
          "Can I self-host it?",
          "Yes. Deploy it to Deno Deploy or run the multi-architecture Docker image.",
        ],
        [
          "How do I report a compatibility issue?",
          "Open a GitHub issue with the route, redacted request, response status, and request ID. Never include your API key.",
        ],
      ],
    },
    footer: {
      title: "Make Agnes fit the tools you already use.",
      action: "View the project on GitHub",
      issue: "Report an issue",
      docs: "Deployment docs",
      independent:
        "Independent open-source project. Not affiliated with Agnes AI or OpenAI.",
      license: "MIT",
    },
  },
  "zh-CN": {
    skip: "跳到主要内容",
    nav: {
      playground: "在线测试",
      compatibility: "接口差异",
      quickstart: "快速开始",
      deploy: "部署",
      faq: "常见问题",
      menu: "打开导航",
      close: "关闭导航",
      github: "查看 GitHub 仓库",
      theme: "切换颜色主题",
      locale: "Switch to English",
    },
    hero: {
      eyebrow: "OPENAI-COMPATIBLE GATEWAY",
      titleA: "一种 OpenAI 格式，",
      titleB: "接入 Agnes 全模态。",
      body:
        "让现有 OpenAI 客户端直接调用 Agnes 对话、图像、图像编辑与视频生成；不使用服务端 API Key，也不做隐式模型映射。",
      primary: "立即测试",
      secondary: "查看 GitHub",
      proof: ["开源", "可自托管", "Key 不落盘"],
      curl: "cURL",
      sdk: "OpenAI SDK",
      copy: "复制示例",
      copied: "已复制",
    },
    playground: {
      eyebrow: "使用你自己的 KEY",
      title: "发起一次真实请求",
      intro:
        "请求从当前浏览器直接发往你选择的网关。Agnes Key 只保留在本页内存中。",
      key: "Agnes API Key",
      keyHint: "不会写入 Cookie、localStorage 或分析服务。",
      show: "显示 Key",
      hide: "隐藏 Key",
      clear: "清除敏感数据",
      base: "网关 Base URL",
      baseHint: "默认使用当前部署地址。",
      advanced: "连接设置",
      destination: "请求目标",
      model: "模型",
      prompt: "提示词",
      message: "消息",
      promptPlaceholder: "描述你希望 Agnes 生成的内容…",
      messagePlaceholder: "用两句话解释网关的作用。",
      stream: "流式返回",
      size: "尺寸",
      count: "图片数量",
      seconds: "时长",
      image: "参考图片",
      drop: "选择 PNG、JPEG 或 WebP 图片",
      fileLimit: "单张图片，最大 20 MiB。",
      remove: "移除图片",
      send: "发送请求",
      cancel: "取消",
      retry: "重试",
      requiredKey: "请输入 Agnes API Key。",
      requiredModel: "模型为必填项，网关会原样透传。",
      requiredPrompt: "请输入提示词或消息。",
      requiredImage: "此工作流需要选择一张图片。",
      invalidImage: "请选择不超过 20 MiB 的 PNG、JPEG 或 WebP 图片。",
      invalidBase: "请输入以 http:// 或 https:// 开头的完整网关地址。",
      request: "请求",
      result: "结果",
      empty: "响应将显示在这里。",
      requesting: "正在等待 Agnes…",
      polling: "视频任务已受理，正在轮询…",
      success: "已完成",
      failed: "请求失败",
      cancelled: "已取消",
      status: "HTTP 状态",
      elapsed: "耗时",
      task: "任务 ID",
      requestId: "请求 ID",
      progress: "任务进度",
      rawRequest: "已脱敏请求",
      rawResponse: "原始响应",
      copyJson: "复制 JSON",
      download: "下载",
      openMedia: "打开媒体",
      noPersistence: "检查器会对 Authorization 脱敏，也不会持久化响应正文。",
    },
    compatibility: {
      eyebrow: "明确转换，不做魔法",
      title: "准确了解每一处差异",
      intro: "网关只转换能够安全抹平的差异；模型名始终原样透传。",
      all: "全部",
      text: "文本",
      images: "图像",
      video: "视频",
      differences: "仅看差异",
      capability: "能力 / 路由",
      request: "OpenAI 输入",
      mapping: "网关行为",
      status: "支持状态",
      pass: "透传",
      transform: "已转换",
      partial: "部分兼容",
      extension: "Agnes 扩展",
      rows: [
        [
          "对话",
          "model, messages, stream",
          "模型原样透传；developer 转为 system；max_completion_tokens 转为 max_tokens。",
          "transform",
        ],
        [
          "图像生成",
          "prompt, model, size, n",
          "size 默认 1024x1024；转换 response_format；n 采用原子并发。",
          "transform",
        ],
        [
          "图像编辑",
          "multipart image / image[]",
          "文件转成 Agnes extra_body.image 中的 Data URI。",
          "transform",
        ],
        [
          "视频创建",
          "prompt, seconds, size",
          "seconds 转为 24 fps 帧数；size 拆为宽高。",
          "transform",
        ],
        [
          "视频查询",
          "GET /v1/videos/{id}",
          "公开 ID 直接使用无状态的 Agnes 任务 ID。",
          "pass",
        ],
        [
          "视频内容",
          "GET /v1/videos/{id}/content",
          "完成后流式代理媒体；thumbnail、spritesheet 暂回退到视频。",
          "partial",
        ],
      ],
    },
    security: {
      eyebrow: "请求透明",
      title: "你的凭据只走最短路径",
      steps: ["当前浏览器", "你的网关", "Agnes AI"],
      body:
        "线上网关没有服务端 API Key。它只转发每次请求携带的 Bearer 凭据，日志仅保留脱敏的请求元数据。",
      memory: "Key 生命周期",
      memoryBody: "只存在于组件内存；可随时清除，关闭标签页后自然释放。",
      storage: "不持久化",
      storageBody: "Key、媒体、提示词和响应均不会进入 localStorage。",
      audit: "可审计",
      auditBody: "可在开源路由处理器中查看完整请求路径。",
      source: "检查源代码",
    },
    quickstart: {
      eyebrow: "五分钟开始",
      title: "把客户端指向网关",
      intro:
        "继续使用 Agnes 模型名和 API Key；只需修改 OpenAI 客户端的 base URL。",
      sdk: "OpenAI SDK",
      curl: "cURL",
      docker: "Docker",
      deno: "Deno Deploy",
      dockerBody:
        "运行已发布镜像，可选配置一个上游 URL；不需要数据库或密钥服务。",
      denoBody:
        "Fork 仓库并连接 Deno Deploy，选择 Fresh preset。默认 Agnes 地址无需配置即可使用。",
      env: "可选环境变量",
      deployLink: "阅读部署指南",
    },
    troubleshooting: {
      eyebrow: "从边缘定位问题",
      title: "常见故障保持可见",
      items: [
        [
          "401 / 403",
          "检查 Agnes Key 以及它是否有权使用目标模型。网关不会替换其他凭据。",
        ],
        [
          "404",
          "检查网关 Base URL 与兼容路由。视频使用 /v1/videos，而不是 /v1/video/generations。",
        ],
        [
          "429",
          "响应来自 Agnes 账户限制。重试前先查看 Retry-After 和原始响应。",
        ],
        [
          "参数错误",
          "确认模型、图片类型、尺寸和视频时长。被忽略的可选字段会列在响应头中。",
        ],
        [
          "5xx 或超时",
          "媒体任务可能耗时较长。可按请求 ID 查日志；若边缘运行时超时，请改用 Docker。",
        ],
      ],
    },
    faq: {
      eyebrow: "常见问题",
      title: "直接回答",
      items: [
        [
          "这是 Agnes AI 官方项目吗？",
          "不是。这是基于 Agnes 公开接口文档构建的独立开源兼容网关。",
        ],
        [
          "网关会保存我的 API Key 吗？",
          "不会。线上服务没有服务端 Key；本测试器只在内存中保留 Key，并随每次请求发送。",
        ],
        [
          "支持哪些模型？",
          "网关不维护模型清单或别名。请填写你的 Agnes 账户实际支持的模型名。",
        ],
        [
          "为什么响应可能与 OpenAI 不同？",
          "部分 Agnes 能力没有完全对应的 OpenAI 表达。兼容矩阵会记录每项透传、转换和部分兼容行为。",
        ],
        [
          "可以自行部署吗？",
          "可以。支持部署到 Deno Deploy，也可运行多架构 Docker 镜像。",
        ],
        [
          "如何报告兼容问题？",
          "请在 GitHub Issue 中提供路由、脱敏请求、响应状态和请求 ID，切勿附带 API Key。",
        ],
      ],
    },
    footer: {
      title: "让 Agnes 接入你已经在用的工具。",
      action: "在 GitHub 查看项目",
      issue: "提交 Issue",
      docs: "部署文档",
      independent: "独立开源项目，与 Agnes AI 或 OpenAI 无隶属关系。",
      license: "MIT",
    },
  },
} as const satisfies Record<Locale, unknown>;
